language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install https://github.com/QuantCrimAtLeeds/PredictCode/zipball/master"

script:
  - pytest --cov=./
  
after_success:
- codecov
